spring:
  application:
    name: Foro Hub API

  datasource:
    url: jdbc:mysql://localhost:3306/foro_hub
    username: root
    password: ADMIN
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
